### ISSUE TITLE
Scroll jumps with GridLayoutManager.SpanSizeLookup

### ISSUE THREAD

**Issue by JonathanMercandalli** [timusus/RecyclerView-FastScroll#21]
##### Scroll position jumps with header and GridLayoutManager(context, 2).

```java
final GridLayoutManager gridLayoutManager = new GridLayoutManager(getActivity(), 2);
gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
    @Override
    public int getSpanSize(int position) {
         return mFileModelCardAdapter.isHeader(position) ?
            gridLayoutManager.getSpanCount() : 1;
    }
});
mRecyclerView.setLayoutManager(gridLayoutManager);
```

**Comment by 410133062** [comment]
I have this problem too

**Comment by timusus** [comment]
This library isn't capable of dealing with rows which differ in size - it assumes all rows are of equal height, and there are a fixed number of items per row.

If you're able to come up with a solution, make a PR and I'll gladly merge it in.

**Comment by timusus** [comment]
This is resolved with the `MeasurableAdapter` interface, see the Readme.

**Comment by JonathanMercandalli** [comment]
Thanks a lot =)

**Comment by 410133062** [comment]
Thanks.
