### ISSUE TITLE
Scroll and section indicator jumps if cells have different heights

### ISSUE THREAD

**Issue by cybergen78** [timusus/RecyclerView-FastScroll#25]
The cells in my example have all equal heights except one (one label wraps and has two lines). Whenever I fast scroll over the one higher cell the scroll and the indicator flickers and jumps up and down.

**Comment by timusus** [comment]
One of the major limitations of of this library is that it assumes all adapter items are of equal height.

**Comment by cybergen78** [comment]
Oh noes! It's a contact name and thus can't be ellipsized.
Are you planning to fix this?

**Comment by timusus** [comment]
Oops, I never finished writing the comment above. 

I don't have a fix in mind for this issue unfortunately. As a workaround, I would suggest hardcoding the number of lines for the text view so they're all the same.

**Comment by cybergen78** [comment]
> Little boxes on the hillside,
> Little boxes made of ticky tacky,
> Little boxes on the hillside,
> Little boxes all the same.

😅

**Comment by jiansheliuxing** [comment]
we can override ths method synchronizeScrollBarThumbOffsetToViewScroll and use item numbers to set the offset

**Comment by timusus** [comment]
Closed with #51
