### ISSUE TITLE
Add support for auto-hide

### ISSUE THREAD

**Issue by iAlex97** [timusus/RecyclerView-FastScroll#3]
It would be nice to have support for the auto-hide feature (like Google Messenger)

**Comment by jaredrummler** [comment]
:+1: 

something like [setFastScrollAlwaysVisible(boolean)](http://developer.android.com/reference/android/widget/AbsListView.html#setFastScrollAlwaysVisible%28boolean%29)

**Comment by jaredrummler** [comment]
I forked this repo and started adding it. I ended up rewriting everything from scratch. Here is my project that has auto-hide and based off the latest changes from Google: https://github.com/jaredrummler/FastScroll-RecyclerView

**Comment by iAlex97** [comment]
Great! I'll check it out and report back as soon as possible

**Comment by timusus** [comment]
There is a PR pending that I hope to accept soon, which supposedly adds support for auto-hide. Have a look at the pending PRs.

@jaredrummler I had a look at your implementation - that certainly isn't 'written from scratch', you've retained some of the hard work I've done, without retaining the license.. that's not very nice!

**Comment by timusus** [comment]
Resolved with #14

**Comment by jaredrummler** [comment]
@timusus It is written using the latest changes from Google. I did use the SectionedAdapter code from your project (which is about ~10 lines). I just updated the project with your name in the license and credit in the README. However, both the projects are 98% written by Google and you didn't keep their name in the license file (I don't blame you, my IDE auto updates the license).

https://github.com/jaredrummler/FastScroll-RecyclerView/commit/583d195e53d7f3f65009e52bdba792fcb53ec007

**Comment by timusus** [comment]
@jaredrummler I'm not trying to be petty, but a lot of work went into that library (more than just the SectionedAdapter, Launcher3's FastScroll required a few difficult modifications to fix some bugs you would take for granted now that they're gone). 

I only wish, as do most open source contributors, to have credit given where it is due. That is why I have credited Launcher3 and provided the license in the readme. I used my own licenses in the Java classes as they have all been heavily modified by myself. 

You're haven't written a FastScroller with the 'latest changes', you've ported things I intentionally removed back into the library and rebranded it as your own own! 

Anyway, it's not a big deal and definitely doesn't warrant this much debate. I appreciate you reinstating the license, thank you.

**Comment by jaredrummler** [comment]
@timusus I didn't use your library as a base. Please go look at the code more carefully. I agree, this does not need a debate. I'm happy to give credit.

**Comment by timusus** [comment]
@jaredrummler there are some specific comments and bug fixes that would indicate otherwise, namely GridLayout support and a very difficult fix resolving lag when using lists containing hundreds of items or more.

I guess I just don't really understand your motivation here. Open source is something sacred and I really don't like to see it abused, especially by another open source contributor. 

To say Google wrote 98% of the code and therefore it's fine to play off as your own work is just unfair. You might appreciate that this came so easy to you because someone already did the hard yards. I'm not saying I did it all, that's not where I'm coming from. But I did work hard on this library, and it's hard to appreciate that when you're looking at the end result.

**Comment by jaredrummler** [comment]
@timusus 

It is pretty easy to prove I didn't use your library as a base.

Does your library have a drawable that is used by the latest marshmallow-mr1-release of Launcher3? No, it doesn't. Mine does. See [Launcher3](https://android.googlesource.com/platform/packages/apps/Launcher3/+/marshmallow-mr1-release/res/drawable/container_fastscroll_popup_bg.xml) and my [library](https://github.com/jaredrummler/FastScroll-RecyclerView/blob/master/lib-fastscrollrecyclerview/src/main/res/drawable/fastscroll_popup_bg.xml).

Does your library have inactive and active colors for the indicator thumb? No, it doesn't. However, my [library](https://github.com/jaredrummler/FastScroll-RecyclerView/blob/master/lib-fastscrollrecyclerview/src/main/java/com/jaredrummler/fastscrollrecyclerview/FastScrollBar.java#L54-55) and the latest [Launcher3](https://android.googlesource.com/platform/packages/apps/Launcher3/+/marshmallow-mr1-release/src/com/android/launcher3/BaseRecyclerViewFastScrollBar.java#L51-52) do.

I could go on and on. Again, I only used a few parts from your library (about ~10 lines). I originally spent a couple hours coding this feature into your project but when I eventually started from scratch.

**Comment by timusus** [comment]
@jaredrummler I can see code I've written, which you've ported, you obviously don't even realise what you've copied across. 

Forget about it man, this is clearly a lost cause. Good luck and I hope you think a little harder on how you credit other people for their work in the future.

**Comment by jaredrummler** [comment]
@timusus I know exactly what I used from your project. Please don't try to lecture someone on contributing to open source. I originally was going to submit a pull request to your project. The project was public for less than 1 day before I added your name to the license and README. This is ridiculous. I think your attitude here is against an open source spirit. You accused me of using your project as a base when I did not. I've already wasted enough of my time here.

**Comment by timusus** [comment]
@jaredrummler my attitude here is against open source spirit? Come off it. I was just defending my own hard work. Shouldn't have been necessary in the first place.
