### ISSUE TITLE
want a gif to present to customers

### ISSUE THREAD

**Issue by BlackDizel** [timusus/RecyclerView-FastScroll#35]
like here https://github.com/FutureMind/recycler-fast-scroll
https://camo.githubusercontent.com/26b1a68095f8cf1e68add244bdcea7fdc376a341/687474703a2f2f692e696d6775722e636f6d2f556771687a75642e676966

**Comment by timusus** [comment]
The great thing about open source is you can download it, compile it, run it and do whatever you want with it.
