### ISSUE TITLE
Scroll Popup not disappearing

### ISSUE THREAD

**Issue by dellisd** [timusus/RecyclerView-FastScroll#36]
On certain devices (Nexus 6P, Nexus 5X, Moto G3, etc.) the section popup doesn't disappear after the user has stopped scrolling.

**Comment by davag** [comment]
I had a similar issue in prod only. The cause was proguard. If you use Proguard you might want to add this line
-keep class com.simplecityapps.recyclerview_fastscroll.*\* { *; }

**Comment by dellisd** [comment]
That fixed it
