### ISSUE TITLE
Scroll thumbnail is not hiding in release builds with obfuscation

### ISSUE THREAD

**Issue by ikravchenko** [timusus/RecyclerView-FastScroll#39]
I am currently adding the following proguard config to fix it:

```
# ---- FastScrollRecycleView ----
-keep class com.simplecityapps.recyclerview_fastscroll.** { *; }
# ---- END FastScrollRecycleView ----
```

Please add a note or include progurd rules into your lib.

**Comment by iAlex97** [comment]
By trial end error I found out that you only need to keep `FastScrollPopup` (it cuts down a few methods) therefore the ProGuard config that I am using is the following:

```
# ------- FastScrollRecycleView START -------
-keep class com.simplecityapps.recyclerview_fastscroll.views.FastScrollPopup { *; }
# ------- FastScrollRecycleView END -------
```

**Comment by timusus** [comment]
Thanks for the info.

I just haven't gotten around to testing this out, which is why I haven't added a proguard rule to the library yet.

**Comment by by-syk** [comment]
I met this issue too and solved it by adding the Proguard rule. Thanks.

**Comment by VladimirWrites** [comment]
Works for me also. It should be added to README.md, and this issue should be closed.
