### ISSUE TITLE
Not working when each item of the recyclerview has two elemnts

### ISSUE THREAD

**Issue by Anis-Vikernes** [timusus/RecyclerView-FastScroll#41]
I followed your tutorial but the problem is that each item in my recyclerview has two elements (in other words two TextViews) and now I get an error on this part : 
`@NonNull
    @Override
    public String getSectionName(int position) {
        return String.valueOf(position);
    }`
PS: I want to set the scrollbar on one element only not the two of them

**Comment by timusus** [comment]
What error are you getting?

**Comment by timusus** [comment]
Not enough information to debug this issue.
