### ISSUE TITLE
ScrollToPosition

### ISSUE THREAD

**Issue by Hitexroid** [timusus/RecyclerView-FastScroll#45]
> java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.scrollToPosition(int)' on a null object reference

**Comment by timusus** [comment]
It sounds like your RecyclerView is null. There's not enough information here for me to do anything with.

**Comment by Hitexroid** [comment]
Just when i use `ScrollToPosition ` returns this error ! please test it.

**Comment by timusus** [comment]
Can you provide a stack trace and some sample code?
