### ISSUE TITLE
Not support StaggeredGridLayoutManager

### ISSUE THREAD

**Issue by by-syk** [timusus/RecyclerView-FastScroll#46]
`LinearLayoutManager` and `GridLayoutManager` are OK, but `StaggeredGridLayoutManager` is not.
The error occurs here:
`com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView`
```
...
LinearLayoutManager layoutManager = ((LinearLayoutManager) getLayoutManager());
...
```

**Comment by timusus** [comment]
As per the readme:

> Supports vertical RecyclerViews using either LinearLayoutManager or GridLayoutManager (including multiple spans).

Sorry, other layout managers are not supported. Taking pull requests though, so if you'd like to figure it out..

**Comment by by-syk** [comment]
Got it. Thanks.
