### ISSUE TITLE
How to hide FastScroll

### ISSUE THREAD

**Issue by Hitexroid** [timusus/RecyclerView-FastScroll#49]
Hi , how to hide and show `fastscroller `by a method like this ?

`FSV.showFastScroller(false);`

**Comment by samoremec** [comment]
There is app:fastScrollEnabled="false" but it does nothing

**Comment by timusus** [comment]
`app:fastScrollEnabled` is not an attribute of this library - I believe this is a recent addition to `RecyclerView` by Google, which is related to their own implementation of `RecyclerView`.

**Comment by timusus** [comment]
Resolved with f2e22af
