### ISSUE TITLE
GridLayoutManager scroll position error

### ISSUE THREAD

**Issue by karimknaebel** [timusus/RecyclerView-FastScroll#5]
The FastScroll thumb only scrolls between 0 & itemCount/2.

**Comment by timusus** [comment]
GridLayoutManager is already supported.

**Comment by kabouzeid** [comment]
Doesn't work for me. I.e. when I set grid size 2 the handle goes at most to the half of the available height.

**Comment by timusus** [comment]
This is due to changes you made to your fork.

**Comment by kabouzeid** [comment]
@timusus I've just checked this, this isn't because of changes in my fork, when you use the current implementation with more elements (200 for example) the same happens.

**Comment by timusus** [comment]
Sorry, my mistake. I did test this, but with 500 items, where the error is not present. Not sure what's going on here!
