### ISSUE TITLE
Scrollbar outside Recyclerview

### ISSUE THREAD

**Issue by Ajtak** [timusus/RecyclerView-FastScroll#53]
Is possible add scrollbar outside RecyclerView?

**Comment by timusus** [comment]
The ScrollBar could be decoupled from the RecyclerView, and if I had my time again, that is the approach I would have preferred.

But this is not currently possible.

**Comment by Ajtak** [comment]
I know, that clear recyclerview its supported with atribute **scrollbarStyle="outsideInset"**, witch make, that scrollbar is outside. 

PS: Your library is best :)

**Comment by Ajtak** [comment]
My idea is same as this:
[![MyIdea](http://i.jafr.eu/i/uyOdQG0ayb_Beznzvupng.png)](http://i.jafr.eu/i/uyOdQG0ayb_Beznzvupng.png)

**Comment by timusus** [comment]
That image is no longer available. Feel free to reopen if you'd like to elaborate on the requirements for this feature.
