### ISSUE TITLE
MeasurableAdapter interface does not exist

### ISSUE THREAD

**Issue by hosseinaminii** [timusus/RecyclerView-FastScroll#54]
Hello
I use `compile 'com.simplecityapps:recyclerview-fastscroll:1.0.15'` in my app.gradle but I can not use FastScrollRecyclerView.MeasurableAdapter interface like sample app for my adapter.
Please guid me, Thanks a lot

**Comment by timusus** [comment]
Sorry, I've screwed up the Readme. The `MeasurableAdapter` interface will be available in `1.0.16`, which I'll push out shortly.
