### ISSUE TITLE
FastScroll triggers SwipeRefreshLayout

### ISSUE THREAD

**Issue by GeniusRUS** [timusus/RecyclerView-FastScroll#57]
When you scroll down, the SwipeRefresh call is triggered. But the scroll goes up perfectly. A temporary solution is to set the SweepRefresh setEnabled(false) on start scrolling and setEnabled(true) on stop

**Comment by ghost** [comment]
Hi,
Same problem, here a horrible tricks but that work

```
swipeRefreshLayout.setOnTouchListener((view, motionEvent) -> {
    boolean triggeredByFastScroll = recyclerView.onTouchEvent(motionEvent);
    if (triggeredByFastScroll) return true;

    return view.onTouchEvent(motionEvent);
});
```

CrabeMan.

**Comment by GeniusRUS** [comment]
**CrabeMan**, thank for your reply.
Yep, I solved this problem in the same way. But the developer would be nice to foresee this possibility "out of the box"

**Comment by timusus** [comment]
I'm not able to reproduce this issue. I've added a `SwipeRefreshLayout` around the `RecyclerView` in the sample project, and it is not triggered at all when fast scrolling.

If you can demonstrate the issue via a fork of the sample project, I'm happy to investigate further.

**Comment by ghost** [comment]
Hi,
You can look at [this example](https://github.com/CrabeMan/RecyclerView-FastScroll/tree/prevent_touch_event_conflict).

CrabeMan.

**Comment by timusus** [comment]
I checked out your example, on the branch `prevent_touch_event_conflict`, and out-commented `recyclerView.preventTouchEventConflict(swipeRefreshLayout);`. I wasn't able to reproduce the issue. (Testing on Nexus 6P running Android 8.1.0).

A few things: 
1. Can you describe how to reproduce the issue, just in case I'm missing something?
2. Which device, ROM and Android version are you experiencing this on? 
3. Can you merge the latest changes into your project?

**Comment by ghost** [comment]
Thanks for your tests, i has actually retest my branch without the `recycleView.preventTouchEventConflict`. I have unfortunately not succeeded to reproduce the bug. But the bug is still present in my other project. I will investigate this, I'll keep you informed.
I'm currently running on Nokia 6 w/ Android 7.1.2


Edit: The problem is because I surround the `FastScrollRecyclerView` with a ` FrameLayout`.
It look like
```
<Android.support.v4.widget.SwipeRefreshLayout>
     <FrameLayout>
         <other.layout />
         <com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView />
         <other.layout />
     </ FrameLayout>
</android.support.v4.widget.SwipeRefreshLayout>
```
By removing the FrameLayout the problem not appear.

Thanks.
CrabeMan.
