### ISSUE TITLE
Make scrollbar track "fullscreen"

### ISSUE THREAD

**Issue by G00fY2** [timusus/RecyclerView-FastScroll#59]
Please allow us to make the grey scrollbar background fullscreen to remove the empty space at the start and end.

**Comment by timusus** [comment]
I don't have time to look at this at the moment, but I'm happy to review a PR, shouldn't take much effort to implement.

**Comment by G00fY2** [comment]
Will see if I find some time to create a PR. 😉

**Comment by tprochazka** [comment]
+1
This will be good. I don't understand why the empty space is there.

**Comment by timusus** [comment]
The empty space is there because that's how the `FastScroll` was styled in Lollipop. 

Should be very simple to change, and I'm happy to accept PR's.

**Comment by HappyDr0id** [comment]
Hello, first of all thank you for this library. When will a release be available with this PR ?
