### ISSUE TITLE
Fastscroller doesn't respect padding.

### ISSUE THREAD

**Issue by karimknaebel** [timusus/RecyclerView-FastScroll#6]
~~This is important to make it work with a collapsing toolbar for example. In this case the bottom padding changes when the toolbar collapses/expands. Because of that, currently a part of the fastscroller moves out of the screen when the toolbar is expanded.~~

Not really related to the CollapsingToolbarLayout, but a definite issue none the less. The FastScroll should respect the padding of its parent.

**Comment by kabouzeid** [comment]
Update: as a workaround the user could probably simply wrap the recyclerview into a framelayout and set the padding to the framelayout.

**Comment by timusus** [comment]
This is not a simple issue of respecting/not respecting padding. The bottom offset of the FastScroll track & handle needs to be adjusted based on the offset behavior of whatever view is pushing it down.

It's not clear what the best approach is here, it depends on the layout behavior of other views in the hierarchy.

Closing this ticket and opening #7.

**Comment by garretyoder** [comment]
Couldn't we just have the fastscroller by padded based on the parent on layout? I'm about to integrate this into my own project so if the solution is as simple as such I'll submit a patch.

**Comment by sagarvasnani** [comment]
When can we expect a solution to this bug? This is really really needed.

**Comment by timusus** [comment]
I'm not sure what the use case for this is. Closing, as I don't think a change is necessary here.

@sagarvasnani feel free to reopen if you can demonstrate the issue you're having.
