### ISSUE TITLE
Grey thumb when normal scrolling / colored when fastscroll

### ISSUE THREAD

**Issue by G00fY2** [timusus/RecyclerView-FastScroll#60]
Would be nice to control the behaviour of the thumb to adapt the current way google showing the scrollbar.

**Comment by timusus** [comment]
Happy to accept PR's, but it's not a goal of mine to make this library match Google's latest designs for the contacts app.

**Comment by G00fY2** [comment]
I understand your point. And tbh Google itself is using plenty of differently styled FastScroller for the Drawer, Phone-App, Contact-App and so on.

I just think that your library is the most "Googlish" one and maybe thats one of the reasons many people like it.

Hope I don't annoy you by maybe posting a few more PR this week.
(I also discovered a small issue when drawing the popup for a new section. Different letter width causes the popup to change its size every time by just a few pixels. Making the popup look restless.)

Thanks for still maintaining this great library!

**Comment by timusus** [comment]
Please go ahead and PR away, it does not annoy me in the slightest, I appreciate any and all contributions! 

Can you open a new issue for the bug you mentioned?
