### ISSUE TITLE
java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by rnitame** [timusus/RecyclerView-FastScroll#69]
```
java.lang.ArithmeticException: divide by zero
               at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.scrollToPositionAtProgress(FastScrollRecyclerView.java:297)
               at com.simplecityapps.recyclerview_fastscroll.views.FastScroller.handleTouchEvent(FastScroller.java:205)
               at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.handleTouchEvent(FastScrollRecyclerView.java:138)
               at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.onTouchEvent(FastScrollRecyclerView.java:118)
               at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2756)
               at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2899)
```

```kotlin
 override fun getSectionName(position: Int): String =
            sections[getSectionForAdapterPosition(position)].name
```

This error happen when scrolling.
Is there a any solution?

**Comment by G00fY2** [comment]
Seems like this ([Line 402 in FastScrollRecyclerView](https://github.com/timusus/RecyclerView-FastScroll/blob/master/recyclerview-fastscroll/src/main/java/com/simplecityapps/recyclerview_fastscroll/views/FastScrollRecyclerView.java#L402)) returns 0 in your RecyclerView which is not expected:
```
stateOut.rowHeight = child.getHeight() + getLayoutManager().getTopDecorationHeight(child) + getLayoutManager().getBottomDecorationHeight(child);
```

Because this height is the divider in [Line 297](https://github.com/timusus/RecyclerView-FastScroll/blob/master/recyclerview-fastscroll/src/main/java/com/simplecityapps/recyclerview_fastscroll/views/FastScrollRecyclerView.java#L297) where your error occurs.

**Comment by rnitame** [comment]
@G00fY2 

I got it.
Is there a workaround for using multiple ViewTypes?

**Comment by G00fY2** [comment]
I don't think so. Unfortunately this means that this implementation is also not working properly with sticky header libraries e.g.

**Comment by rnitame** [comment]
I see.

> Unfortunately this means that this implementation is also not working properly with sticky header libraries e.g.

Should I make this issue separately? (By the way, I use https://github.com/ShamylZakariya/StickyHeaders )

**Comment by rnitame** [comment]
@G00fY2 How about this?
https://github.com/timusus/RecyclerView-FastScroll/issues/69#issuecomment-355200068

**Comment by G00fY2** [comment]
Relates to #42.
There is no "easy" way to support this. Also haven't seen a Google app which has this feature. They use [another approach](https://user-images.githubusercontent.com/1990806/35194704-cb0d2d96-feb7-11e7-9e4c-640f6fd56634.png).


Also unfortunately @timusus seems to currently not maintain the library.:cry:

**Comment by timusus** [comment]
I'll happily consider your PR.

**Comment by G00fY2** [comment]
I would appreciate it if you could deploy the last changes in the meantime.
Will may try to look into extending support for variable item sizes.

**Comment by timusus** [comment]
@rnitame 

>Is there a workaround for using multiple ViewTypes?

Yes, see the `MeasurableAdapter` interface in the Readme.

**Comment by rnitame** [comment]
@timusus I see. Thanks!

**Comment by timusus** [comment]
This divide by zero exception seems to occur if you have zero-height items in your adapter. I'm not sure when this would ever be the case.. 

If you do have zero-height items in your adapter, then you need to implement `MeasurableAdapter` in your `RecyclerViewAdapter`, and provide the heights of your views, so the `FastScrollRecyclerView` can draw the itself accurately. 

I can't reproduce this issue with the `MeasurableAdapter` implemented.

**Comment by rnitame** [comment]
FYI, I fixed this issue what I increment a version without more development 👍
