### ISSUE TITLE
Make xml field app:fastScrollPopupBackgroundSize accessible via Java code

### ISSUE THREAD

**Issue by benjaminglatzeder** [timusus/RecyclerView-FastScroll#70]
There are public methods like `recyclerView.setPopupTextColor();` and `recyclerView.setPopupTextSize();` but no method to set the popup background size

**Comment by G00fY2** [comment]
The size of the popup background get calculated dynamically by measuring the actual text bounds of the shown text inside.
By what criteria would you like to set a fixed size? This gets pretty hard when you can use numeric, all lower or all upper case characters.

You can see the logic in my pull request from #63.

**Comment by benjaminglatzeder** [comment]
After I changed the value of app:fastScrollPopupBackgroundSize a few times and compared the visual results, I realized that the default size is on point. Since I don't think my change request is necessary and I'm the OP I'll close this ticket.
