### ISSUE TITLE
Recycler view does not support Action mode

### ISSUE THREAD

**Issue by amit-bhandari** [timusus/RecyclerView-FastScroll#72]
Please help!

Unable to start action mode using this recycler view. Always getting null action mode.

Tried support library Recycler view and it worked.

**Comment by timusus** [comment]
Can you please provide a code sample, or a branch demonstrating the issue?

**Comment by amit-bhandari** [comment]
I got the action mode working, I don't know what I was doing wrong back then. Sorry :(
