### ISSUE TITLE
Style Scrollbar in a rounder way

### ISSUE THREAD

**Issue by panmona** [timusus/RecyclerView-FastScroll#76]
Is it possible to style my scrollbar from this library in a rounder way like in this example? How could I do that?

![](https://raw.githubusercontent.com/L4Digital/FastScroll/master/fastscroll_example.png)

**Comment by timusus** [comment]
No, this isn't possible.

You could add this functionality yourself by forking the repo and making the appropriate changes to the FastScroll Thumb.

**Comment by panmona** [comment]
Okay :/ Thanks for the answer though 👍 !

**Comment by timusus** [comment]
I'd highly recommend forking the library. It's much simpler than it might first appear.
