### ISSUE TITLE
Set the manager reversed, fast scroll not working correctly.

### ISSUE THREAD

**Issue by csshuai** [timusus/RecyclerView-FastScroll#81]
Set the manager reversed, fast scroll not working correctly.

```
    LinearLayoutManager manager = new LinearLayoutManager(mActivity);
    manager.setReverseLayout(true);
```

**Comment by timusus** [comment]
Can you please describe in what way the Fast Scroll isn't working correctly?

**Comment by csshuai** [comment]
![ezgif-3-ef5d40cdea](https://user-images.githubusercontent.com/1501906/40467168-6071db08-5f5b-11e8-851d-3ac23f2416fd.gif)

**Comment by qwert2603** [comment]
Any thougths how to correct this?
