### ISSUE TITLE
Unable to compile with sdk version 28

### ISSUE THREAD

**Issue by arams** [timusus/RecyclerView-FastScroll#84]
I get below error when i compile for 28

Warning: com.netmine.rolo.fastscroll.FastScrollPopup: can't find referenced method 'int save(int)' in library class android.graphics.Canvas

In different library I saw this fix. This might be applicable for us. 

https://github.com/umano/AndroidSlidingUpPanel/pull/922/commits/7af57e82bfdac401ea1a0b6a105442d427e9c5e7

**Comment by timusus** [comment]
Resolved with #96
