### ISSUE TITLE
Canvas.save(int) no longer exists as of API level 28

### ISSUE THREAD

**Issue by ghost** [timusus/RecyclerView-FastScroll#88]
When I build the application with ProGuard, I get the following warning.

    Warning: com.simplecityapps.recyclerview_fastscroll.views.FastScrollPopup: can't find referenced method 'int save(int)' in library class android.graphics.Canvas

This method was [deprecated](https://developer.android.com/sdk/api_diff/26/changes/android.graphics.Canvas) in API level 26 (along with `Canvas.MATRIX_SAVE_FLAG`) and [removed](https://developer.android.com/sdk/api_diff/28/changes/android.graphics.Canvas) in API level 28.

Curiously, the library still seems to function correctly if I insert a `dontwarn` into the ProGuard rules; so that is a viable work-around for the time being.

    -dontwarn com.simplecityapps.recyclerview_fastscroll.views.FastScrollPopup

**Comment by timusus** [comment]
Resolved with #96
